export const translations: Record<string, Record<string, string>> = {
  EN: {
    appName: "FormFlow Pro",
    tagline: "The Best Form Builder By BORHAN",
    dashboard: "Dashboard",
    myForms: "My Forms",
    createNewForm: "Create New Form",
    logout: "Log Out",
    login: "Log In",
    register: "Register",
    email: "Email Address",
    password: "Password",
    name: "Full Name",
    noAccount: "Don't have an account?",
    alreadyAccount: "Already have an account?",
    forms: "Forms",
    responses: "Responses",
    views: "Views",
    completionRate: "Completion Rate",
    recentForms: "Recent Forms",
    noForms: "You haven't created any forms yet.",
    createFirstForm: "Create your first form to start collecting responses!",
    title: "Title",
    description: "Description",
    unnamedForm: "Unnamed Form",
    formDescriptionPlaceholder: "Provide a description for your form...",
    save: "Save",
    saving: "Saving...",
    preview: "Preview",
    share: "Share",
    settings: "Settings",
    theme: "Theme",
    questions: "Questions",
    addQuestion: "Add Question",
    required: "Required",
    placeholder: "Placeholder text...",
    options: "Options",
    addOption: "Add Option",
    delete: "Delete",
    duplicate: "Duplicate",
    conditionalLogic: "Conditional Logic",
    enableLogic: "Enable Conditional Logic",
    showIf: "Show this question if",
    selectQuestion: "Select a question",
    equals: "Equals",
    notEquals: "Does not equal",
    contains: "Contains",
    hasValue: "Has any value",
    active: "Active",
    inactive: "Inactive",
    isActive: "Form is accepting responses",
    limitResponses: "Limit total responses (0 for unlimited)",
    closeMessage: "Close Message",
    autoExcelSync: "Enable Live Excel Sync (Auto-Save)",
    themePreset: "Theme Style",
    glowColor: "Glow Accent Color",
    viewSubmissions: "View Submissions",
    backToDashboard: "Back to Dashboard",
    downloadExcel: "Export Excel (CSV)",
    downloadPDF: "Print Form Layout",
    qrCode: "Form QR Code",
    submit: "Submit",
    submittedSuccess: "Thank you! Your response has been submitted successfully.",
    submitAnother: "Submit another response",
    formClosed: "This form is closed.",
    loading: "Loading form...",
    fileUploadBtn: "Choose File",
    signatureClear: "Clear Signature",
    ratingLabel: "Rating",
    yes: "Yes",
    no: "No",
    sectionTitle: "Section Header",
    welcomeBack: "Welcome back!",
    createAccount: "Create a new developer account",
    noResponsesYet: "No responses have been submitted yet.",
    responseAt: "Submitted at",
    answersHeader: "Form Submission Answers",
    excelSyncActive: "Excel Live Sync is active for this sheet"
  },
  BN: {
    appName: "ফর্মফ্লো প্রো",
    tagline: "বোরহান দ্বারা তৈরি সেরা ফর্ম বিল্ডার",
    dashboard: "ড্যাশবোর্ড",
    myForms: "আমার ফর্মসমূহ",
    createNewForm: "নতুন ফর্ম তৈরি করুন",
    logout: "লগ আউট",
    login: "লগ ইন",
    register: "নিবন্ধন",
    email: "ইমেইল ঠিকানা",
    password: "পাসওয়ার্ড",
    name: "পূর্ণ নাম",
    noAccount: "অ্যাকাউন্ট নেই?",
    alreadyAccount: "ইতিমধ্যে অ্যাকাউন্ট আছে?",
    forms: "ফর্ম",
    responses: "উত্তরসমূহ",
    views: "ভিউ",
    completionRate: "সম্পূর্ণতার হার",
    recentForms: "সাম্প্রতিক ফর্ম",
    noForms: "আপনি এখনও কোনো ফর্ম তৈরি করেননি।",
    createFirstForm: "উত্তর সংগ্রহ শুরু করতে আপনার প্রথম ফর্ম তৈরি করুন!",
    title: "শিরোনাম",
    description: "বর্ণনা",
    unnamedForm: "নামহীন ফর্ম",
    formDescriptionPlaceholder: "আপনার ফর্মের জন্য একটি বর্ণনা প্রদান করুন...",
    save: "সংরক্ষণ করুন",
    saving: "সংরক্ষণ হচ্ছে...",
    preview: "প্রিভিউ",
    share: "শেয়ার",
    settings: "সেটিংস",
    theme: "থিম",
    questions: "প্রশ্নসমূহ",
    addQuestion: "প্রশ্ন যোগ করুন",
    required: "বাধ্যতামূলক",
    placeholder: "প্লেসহোল্ডার টেক্সট...",
    options: "অপশনসমূহ",
    addOption: "অপশন যোগ করুন",
    delete: "মুছে ফেলুন",
    duplicate: "ডুপ্লিকেট করুন",
    conditionalLogic: "শর্তাধীন লজিক",
    enableLogic: "শর্তাধীন লজিক চালু করুন",
    showIf: "এই প্রশ্নটি দেখান যদি",
    selectQuestion: "একটি প্রশ্ন নির্বাচন করুন",
    equals: "সমান হয়",
    notEquals: "সমান না হয়",
    contains: "থাকলে",
    hasValue: "যেকোনো মান থাকলে",
    active: "সক্রিয়",
    inactive: "নিষ্ক্রিয়",
    isActive: "ফর্ম উত্তর গ্রহণ করছে",
    limitResponses: "মোট উত্তরের সীমা (সীমাহীন এর জন্য ০)",
    closeMessage: "বন্ধের বার্তা",
    autoExcelSync: "লাইভ এক্সেল সিঙ্ক চালু করুন (স্বয়ংক্রিয় সংরক্ষণ)",
    themePreset: "থিম স্টাইল",
    glowColor: "গ্লো এক্সেন্ট কালার",
    viewSubmissions: "উত্তরসমূহ দেখুন",
    backToDashboard: "ড্যাশবোর্ডে ফিরে যান",
    downloadExcel: "এক্সেল এক্সপোর্ট (CSV)",
    downloadPDF: "ফর্ম লেআউট প্রিন্ট করুন",
    qrCode: "ফর্ম কিউআর কোড",
    submit: "জমা দিন",
    submittedSuccess: "ধন্যবাদ! আপনার উত্তর সফলভাবে জমা দেওয়া হয়েছে।",
    submitAnother: "আরেকটি উত্তর জমা দিন",
    formClosed: "এই ফর্মটি বর্তমানে বন্ধ আছে।",
    loading: "ফর্ম লোড হচ্ছে...",
    fileUploadBtn: "ফাইল নির্বাচন করুন",
    signatureClear: "স্বাক্ষর মুছুন",
    ratingLabel: "রেটিং",
    yes: "হ্যাঁ",
    no: "না",
    sectionTitle: "সেকশন হেডার",
    welcomeBack: "আবার স্বাগতম!",
    createAccount: "নতুন ডেভেলপার অ্যাকাউন্ট তৈরি করুন",
    noResponsesYet: "এখনও কোন উত্তর জমা দেওয়া হয়নি।",
    responseAt: "জমা দেওয়ার সময়",
    answersHeader: "ফর্ম জমার উত্তরসমূহ",
    excelSyncActive: "এই শিটের জন্য এক্সেল লাইভ সিঙ্ক সক্রিয় আছে"
  }
};

export function getTranslation(lang: string, key: string): string {
  const dict = translations[lang] || translations["EN"];
  return dict[key] || translations["EN"][key] || key;
}
